"""Initial tables

Revision ID: 0c482be5f965
Revises: 
Create Date: 2022-10-30 17:46:22.815294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c482be5f965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RootWebsites',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('internal_id', name=op.f('pk_RootWebsites'))
    )
    op.create_index(op.f('ix_RootWebsites_url_hash'), 'RootWebsites', ['url_hash'], unique=True)
    op.create_table('VisitedWebsites',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('root_website_id', sa.Integer(), nullable=True),
    sa.Column('url_hash', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['root_website_id'], ['RootWebsites.internal_id'], name=op.f('fk_VisitedWebsites_root_website_id_RootWebsites')),
    sa.PrimaryKeyConstraint('internal_id', name=op.f('pk_VisitedWebsites'))
    )
    op.create_index(op.f('ix_VisitedWebsites_url_hash'), 'VisitedWebsites', ['url_hash'], unique=True)
    op.create_table('WebsiteMetadata',
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('contained_urls', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['VisitedWebsites.internal_id'], name=op.f('fk_WebsiteMetadata_website_id_VisitedWebsites'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebsiteMetadata')
    op.drop_index(op.f('ix_VisitedWebsites_url_hash'), table_name='VisitedWebsites')
    op.drop_table('VisitedWebsites')
    op.drop_index(op.f('ix_RootWebsites_url_hash'), table_name='RootWebsites')
    op.drop_table('RootWebsites')
    # ### end Alembic commands ###
