"""Use just one table.

Revision ID: 4ccc7a97ede7
Revises: 0c482be5f965
Create Date: 2022-10-31 17:47:02.530287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccc7a97ede7'
down_revision = '0c482be5f965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebsiteMetadata')
    op.drop_table('VisitedWebsites')
    op.drop_table('RootWebsites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RootWebsites',
    sa.Column('insertion_time', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('internal_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('url_hash', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('internal_id', name='pk_RootWebsites')
    )
    op.create_table('VisitedWebsites',
    sa.Column('insertion_time', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('internal_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('root_website_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url_hash', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['root_website_id'], ['RootWebsites.internal_id'], name='fk_VisitedWebsites_root_website_id_RootWebsites'),
    sa.PrimaryKeyConstraint('internal_id', name='pk_VisitedWebsites')
    )
    op.create_table('WebsiteMetadata',
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('contained_urls', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['VisitedWebsites.internal_id'], name='fk_WebsiteMetadata_website_id_VisitedWebsites')
    )
    # ### end Alembic commands ###
