"""Add books table.

Revision ID: 4d613912bd8c
Revises: d433a433d29a
Create Date: 2022-11-06 18:14:36.532685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d613912bd8c'
down_revision = 'd433a433d29a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('upc', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('number_of_copies', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('book_id', name=op.f('pk_books'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
