"""One initial table.

Revision ID: d433a433d29a
Revises: 
Create Date: 2022-10-31 18:19:41.647903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd433a433d29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VisitedWebsites',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('root_url', sa.String(length=1000), nullable=False),
    sa.Column('root_url_hash', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('internal_id', name=op.f('pk_VisitedWebsites'))
    )
    op.create_index(op.f('ix_VisitedWebsites_url_hash'), 'VisitedWebsites', ['url_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VisitedWebsites_url_hash'), table_name='VisitedWebsites')
    op.drop_table('VisitedWebsites')
    # ### end Alembic commands ###
